
--🎆✨🎉 WELCOME 🎉✨🎆
--1.-Execute Query OracleCloud(CTRL + ENTER) ▶️
--2.-Stop Query OracleCloud (CTRL+SHIFT+ ENTER)🟥
--3.-Add OracleCloud Connection(CTRL+SHIFT+ A) 🌩️
--4-LogOut OracleCloudDataBase Extension

--VIEWS
--CTRL+SHIFT+P  >Explorer: Fucus on Conecctions View
--CTRL+SHIFT+P  >User View Container: Fucus on Tables View

----Simple query
SELECT INVOICE_ID,VENDOR_ID,INVOICE_CURRENCY_CODE FROM AP_INVOICES_ALL;
----Example query with params
:P_INVOICE_ID=30 
SELECT INVOICE_ID,VENDOR_ID,INVOICE_CURRENCY_CODE FROM AP_INVOICES_ALL WHERE INVOICE_ID=:P_INVOICE_ID;

:P_INVOICE_ID=30 
SELECT INVOICE_ID,VENDOR_ID,INVOICE_CURRENCY_CODE FROM AP_INVOICES_ALL WHERE INVOICE_ID IN(:P_INVOICE_ID);

:P_INVOICE_ID='%30%' 
SELECT INVOICE_ID,VENDOR_ID,INVOICE_CURRENCY_CODE FROM AP_INVOICES_ALL WHERE INVOICE_ID LIKE :P_INVOICE_ID;

		